// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0wxqvG2dBz17GjF4oqLHlvfkD2IWuVT0',
    appId: '1:697970572506:web:886d438fb4fde572f479e3',
    messagingSenderId: '697970572506',
    projectId: 'auth-4351d',
    authDomain: 'auth-4351d.firebaseapp.com',
    storageBucket: 'auth-4351d.appspot.com',
    measurementId: 'G-T191827T3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCasZIlOvNEyZM11us2NkMe9Kyw4JNL-i0',
    appId: '1:697970572506:android:52263f6cb67a4b3bf479e3',
    messagingSenderId: '697970572506',
    projectId: 'auth-4351d',
    storageBucket: 'auth-4351d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtpl4K5SZtJYkjR5H7Ka7G7nE9EIsBQF8',
    appId: '1:697970572506:ios:852ba1818f17b35bf479e3',
    messagingSenderId: '697970572506',
    projectId: 'auth-4351d',
    storageBucket: 'auth-4351d.appspot.com',
    iosBundleId: 'com.example.authModel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtpl4K5SZtJYkjR5H7Ka7G7nE9EIsBQF8',
    appId: '1:697970572506:ios:852ba1818f17b35bf479e3',
    messagingSenderId: '697970572506',
    projectId: 'auth-4351d',
    storageBucket: 'auth-4351d.appspot.com',
    iosBundleId: 'com.example.authModel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0wxqvG2dBz17GjF4oqLHlvfkD2IWuVT0',
    appId: '1:697970572506:web:8ed89fb405e3ca7ff479e3',
    messagingSenderId: '697970572506',
    projectId: 'auth-4351d',
    authDomain: 'auth-4351d.firebaseapp.com',
    storageBucket: 'auth-4351d.appspot.com',
    measurementId: 'G-M6G9K906G1',
  );
}
