// lib/main.dart
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import 'auth/presentation/manager/auth_cubit.dart';
import 'auth/presentation/manager/auth_state.dart';
import 'auth/presentation/pages/home_screen.dart';
import 'auth/presentation/pages/sign_in_screen.dart';
import 'auth/presentation/pages/sign_up_screen.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'service_locator.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  setupLocator();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({super.key});

  final AuthCubit authCubit = AuthCubit();

  @override
  Widget build(BuildContext context) {
    return BlocProvider<AuthCubit>(
      create: (context) => authCubit,
      child: MaterialApp(
        title: 'Auth App',
        routes: {
          '/signin': (context) => SignInScreen(),
          '/signup': (context) => SignUpScreen(),
          '/home': (context) => HomeScreen(),
        },
        home: BlocBuilder<AuthCubit, AuthState>(
          builder: (context, state) {
            if (state is Authenticated) {
              return const HomeScreen();
            } else if (state is Unauthenticated || state is AuthInitial) {
              return SignInScreen();
            } else if (state is AuthLoading) {
              return const Center(child: CircularProgressIndicator());
            } else if (state is AuthError) {
              return SignInScreen();
            } else {
              return SignInScreen();
            }
          },
        ),
      ),
    );
  }
}
